version: '3.9'

services:
  db:
    container_name: db
    # image: postgres
    build: ./docker
    restart: unless-stopped
    networks:
    - external
    ports:
    - 5432:5432
    volumes:
    - db:/var/lib/postgresql/data
    env_file:
    - .env

  backend:
    container_name: backend
    build: ./backend
    networks:
    - external
    ports:
    - 3000:3000
    - 3002:3002
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
    - external
    ports:
    - 5173:5173
    restart: unless-stopped
    depends_on:
      - db, backend
  
networks:
  external:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${PWD}/docker/dbfolder
