version: '3.9'

services:
  db:
    container_name: db
    build: ./docker
    restart: unless-stopped
    networks:
    - external
    ports:
    - 5432:5432
    env_file:
    - .env
 
networks:
  external:
    driver: bridge
