version: '3.9'

services:
  db:
    container_name: db
    # image: postgres
    build: ./docker/db
    restart: unless-stopped
    networks:
    - external
    ports:
    - 5432:5432
    volumes:
    - db:/var/lib/postgresql/data
    env_file:
    - .env

  node:
    container_name: node
    build: ./backend
    networks:
    - external
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - web:/var/www/html
    depends_on:
      - db
  
networks:
  external:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${VOL_DIR}db
  web:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${VOL_DIR}web