version: '3.9'

services:
  db:
    container_name: db
    build: ./docker/db
    restart: unless-stopped
    networks:
    - internal
    volumes:
    - db:/var/lib/postgresql/data
    env_file:
    - .env

  node:
    container_name: node
    build: ./docker/node
    networks:
    - external
    - internal
    ports:
    - 80:80
    restart: unless-stopped
    volumes:
    - web:/var/www/html
    depends_on:
      - db
  
networks:
  external:
    driver: bridge
  internal:

volumes:
  db:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${VOL_DIR}db
  web:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${VOL_DIR}web