FROM 	node:current-bullseye-slim


# COPY	config/nginx.conf /etc/nginx/sites-available/default
# COPY	config/dhparam.pem /etc/ssl/certs/dhparam.pem 
# COPY	config/nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
# COPY	config/nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt

# CMD	["bash"]